const OK_STATUS_CODE = 200;
const CREATED_STATUS_CODE = 201;
const BAD_REQUEST_STATUS_CODE = 400;
const AUTHENTICATION_ERROR_STATUS_CODE = 401;
const FORBIDDEN_ERROR_STATUS_CODE = 403;
const RESOURCE_NOT_FOUND_STATUS_CODE = 404;
const DUPLICATION_ERROR_STATUS_CODE = 409;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;

module.exports = {
  OK_STATUS_CODE,
  CREATED_STATUS_CODE,
  BAD_REQUEST_STATUS_CODE,
  AUTHENTICATION_ERROR_STATUS_CODE,
  FORBIDDEN_ERROR_STATUS_CODE,
  RESOURCE_NOT_FOUND_STATUS_CODE,
  DUPLICATION_ERROR_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE
};
